### ISSUE TITLE
Page Wont Build

### ISSUE THREAD

**Issue by reganbp** [reganbp/reganbp.github.io#1]
So I am using a bootstrap template that I have seen others use, but I can't get it build the page to get my portfolio online.  When I push the new code to master I get an email back saying

```
Subject: Page build failed

The page build failed with the following error:

A file was included in `example.html` that is a symlink or does not exist in your `_includes` directory.
```

so I followed to the link in the github help section (https://help.github.com/articles/page-build-failed-file-is-a-symlink/) and I followed the troubleshooting steps but can't seem to find the problem.

The trouble shoot steps are 
```
1. Use your favorite text editor to open the file mentioned in the build failure email.
2. Search for the include tag to see where you've referenced other files. For example: {% include cool_header.html %}.
3. Copy or move any symlinked files into the _includes directory of your GitHub Pages repository.
4. Commit and push to your GitHub Pages repository on GitHub to trigger another build on the server.
```
When I search for `{% include` like they referrenced in step 2, and found six examples.  I then checked the _includes file but, these files were already there (https://github.com/reganbp/reganbp.github.io/tree/master/node_modules/magnific-popup/website/_includes) this is the _includes directory I think i need them in and they are in fact in that directory.

So I do not know exactly what is going on with this.  Please let me know that I didnt completely screw this up

**Comment by reganbp** [comment]
The template I used can be found at either link (one is the repo , on is a website with a .zip file download, but they are  the same versions of the template)

repo - https://github.com/BlackrockDigital/startbootstrap-creative
and their web page for it - https://startbootstrap.com/template-overviews/creative/

**Comment by cpearce31** [comment]
Hey Brendan! Try navigating to that `_includes` directory in your terminal and doing `file *`. That will show you a list of files including their types. Symlinked files will show up like this:
```
example_symlink: symbolic link to /home/caleb/.bashrc
```
do you see any symlinks there?

**Comment by reganbp** [comment]
no, the terminal shows

```
analytics.html:  HTML document text, ASCII text, with very long lines
build-tool.html: HTML document text, ASCII text, with very long lines
examples.html:   HTML document text, ASCII text, with very long lines
index.html:      HTML document text, ASCII text, with very long lines
logo.html:       HTML document text, ASCII text
signup.html:     HTML document text, ASCII text
```

but nothing that says `symbolic link`

**Comment by cpearce31** [comment]
It seems like that directory `magnific-popup/website` is just internal documentation for that NPM package, and possible not actually used by your app at all. Probably not the most elegant fix but I'd try just deleting that `website` directory.

**Comment by reganbp** [comment]
That did appear to fix it .  (side note once this file was deleted the the page failed to load at the next documentation for an npm package that had some sort of error, in all I believe I had to remove 7 README's from node_modules to get the page up, but it does appear to be up and running)

Thank You
